import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import CustomProvider from "./providers";
import "./globals.css";
import SideBar from "~/components/sidebar/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// this is the starting point of our app in next js
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-100`}
      >
        <CustomProvider>
          <div className="flex flex-row flex-grow">
            <SideBar />
            <main className="flex-1">{children}</main>
          </div>
        </CustomProvider>
      </body>
    </html>
  );
}
